### ISSUE TITLE
ffmpeg not working

### ISSUE THREAD

**Issue by onhate** [taf2/speech2text#5]
Hello there!

I am tryring to use speech2text in a graduation project but when I  this code is executed, creating a Speech::AudioSplitter

```
  self.duration = Duration.new(`ffmpeg -i #{file} 2>&1`.strip.scan(/Duration: (.*),/).first.first)
```

an erro is thrown: _NoMethodError: undefined method `first' for nil:NilClass_
cause is not able to execute ffmpeg, I am using linux and I have ffmpeg installed, how does this line works??

**Comment by taf2** [comment]
You may need to modify that regex, see what ffmpeg prints out when you run

ffmpeg -i your-file

See if the Duration: line is present?

**Comment by onhate** [comment]
I found the error, the file I sento to this method was with wrong path, so I will add an validation if file exists before do anything, cause the error that is shown is not clear.

Thanks!
